### ISSUE TITLE
WebChimeraPlayerNW cannot work?

### ISSUE THREAD

**Issue by hxzqlh** [jaruba/WebChimeraPlayerNW#1]
I have download WebChimeraPlayerNW and tried to run under `Win7 32bit` but when I click a sublink of `Demo Usage`, it failed and promted a error dialog. The error msg saied:

> Failed to create OpenGL context for format QSuraceFormat(.....)
> 
> This is most likely caused by not having the necessary graphics drivers installed.
> 
> ......Make sure the ANGLE Open GL ES 2.0 emulation libraries(libEGL.dll, libGLESv2.dll and d3dcompileer_*.dll) are available int the app excutable's directory or in a location listed in PATH

But I found `libEGL.dll, libGLESv2.dll and d3dcompileer_*.dll` are in the WebChimeraPlayerNW.

**Comment by jaruba** [comment]
[WebChimera Player](https://github.com/jaruba/WebChimeraPlayer) NW.js demo is deprecated as it is based on [WebChimera NPAPI Plugin](https://github.com/RSATom/WebChimera) (browser plugin).

Since then we've made [WebChimera.js](https://github.com/RSATom/WebChimera.js) that is made especially for NW.js and Electron. For it, we've made [WebChimera.js Player](https://github.com/jaruba/wcjs-player).

**WebChimera.js Player** has two demo apps for NW.js and Electron:
- [Single Video Demo](https://github.com/jaruba/node-vlcPlayer-demo)
- [Multiscreen Demo](https://github.com/jaruba/node-vlc-multiscreen)

**Comment by jaruba** [comment]
If you would (for any reason), prefer using WebChimera NPAPI Plugin and WebChimera Player with NW.js (instead of the recommended WebChimera.js and WebChimera.js Player), then you should make an issue report at [WebChimera NPAPI Plugin](https://github.com/RSATom/WebChimera) as that is the C++ side of WebChimera that does video processing / rendering for this demo.

**Comment by hxzqlh** [comment]
thanks for your answer! @jaruba 

I have been searching for some palyer which can be plugin into `nw.js` and can play almost any media format. `WebChimera.js` is the best solution by now.

By the way, Since `nw.js` now can work on win/linux/osx,  is  `WebChimera.js` cross platform too?

**Comment by hxzqlh** [comment]
I just tried [WebChimera.js Player](https://github.com/jaruba/wcjs-player), but when I run `npm install`, it seemed promt error info link this:

```
hxz@pc0170:~/workspace/nw.js/wcjs-player$ npm install
|
> webchimera.js@0.1.38 install /Users/hxz/workspace/nw.js/wcjs-player/node_modules/wcjs-renderer/node_modules/webchimera.js
> node rebuild.js

info DIST Downloading distribution files.
http DIST   - http://node-webkit.s3.amazonaws.com/v0.12.3/nw-headers-v0.12.3.tar.gz
info CMD CLEAN
info RUN cmake -E remove_directory "/Users/hxz/workspace/nw.js/wcjs-player/node_modules/wcjs-renderer/node_modules/webchimera.js/build"
info CMD CONFIGURE
info RUN cmake "/Users/hxz/workspace/nw.js/wcjs-player/node_modules/wcjs-renderer/node_modules/webchimera.js" --no-warn-unused-cli -DCMAKE_BUILD_TYPE="Release" -DCMAKE_LIBRARY_OUTPUT_DIRECTORY="/Users/hxz/workspace/nw.js/wcjs-player/node_modules/wcjs-renderer/node_modules/webchimera.js/build/Release" -DCMAKE_JS_INC="/Users/hxz/.cmake-js/nw-x64/v0.12.3/src;/Users/hxz/.cmake-js/nw-x64/v0.12.3/deps/v8/include;/Users/hxz/.cmake-js/nw-x64/v0.12.3/deps/uv/include" -DNODE_RUNTIME="nw" -DNODE_RUNTIMEVERSION="0.12.3" -DNODE_ARCH="x64" -DCMAKE_C_COMPILER="clang" -DCMAKE_CXX_COMPILER="clang++" -DCMAKE_CXX_FLAGS="-D_DARWIN_USE_64_BIT_INODE=1 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DBUILDING_NODE_EXTENSION -w -std=c++11" -DCMAKE_SHARED_LINKER_FLAGS="-undefined dynamic_lookup"
Not searching for unused variables given on the command line.
-- The C compiler identification is Clang 7.0.0
-- The CXX compiler identification is Clang 7.0.0
-- Check for working C compiler: /usr/bin/clang
-- Check for working C compiler: /usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/clang++
-- Check for working CXX compiler: /usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBVLC_LIBRARY
    linked by target "libvlc_wrapper" in directory /Users/hxz/workspace/nw.js/wcjs-player/node_modules/wcjs-renderer/node_modules/webchimera.js/deps/libvlc_wrapper

-- Configuring incomplete, errors occurred!
See also "/Users/hxz/workspace/nw.js/wcjs-player/node_modules/wcjs-renderer/node_modules/webchimera.js/build/CMakeFiles/CMakeOutput.log".
ERR! OMG Process terminated: 1
Unhandled rejection Error: Process terminated: 1
    at ChildProcess.<anonymous> (/Users/hxz/workspace/nw.js/wcjs-player/node_modules/wcjs-renderer/node_modules/webchimera.js/node_modules/cmake-js/lib/es5/cMake.js:738:18)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
```

can you tell me how to run this demo? or is my enviment not ok?

my env:

> mac osx yosemite v10.10.5, 64 bit; nw.js v0.12.3

**Comment by jaruba** [comment]
Issue moved to https://github.com/jaruba/node-vlcPlayer-demo/issues/6
